C:\Users\SEDUC\Desktop\PROJETOS\omni_gerador_artigos\venv\Lib\site-packages\_pytest\config\__init__.py:328: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: ModuleNotFoundError: No module named 'domain.orm_models' (from D:\PROJETOS\SISTEMAS\omni_writer\tests\integration\conftest.py)
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ImportError while loading conftest 'D:\PROJETOS\SISTEMAS\omni_writer\tests\integration\conftest.py'.
tests\integration\conftest.py:7: in <module>
    from domain.models import ArticleOutput
domain\models.py:10: in <module>
    from .orm_models import *
E   ModuleNotFoundError: No module named 'domain.orm_models'
